version: '3.1'

services:

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: phpmyadmin
       ports:
          - 8081:80
       environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: password
          PMA_HOST: mariadb
  tomcat:
       image: bitnami/tomcat:latest
       container_name: tomcat
       environment:
          - TOMCAT_USERNAME=root
          - TOMCAT_PASSWORD=password
          - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1
       ports:
         - 8080:8080
       volumes:
         - ./tomcat-users.xml:/opt/bitnami/tomcat/conf/tomcat-users.xml
         - ./context.xml:/opt/bitnami/tomcat/conf/context.xml
  jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        volumes:
            - /home/ubuntu/environment/jenkins_home:/var/jenkins_home 
        ports: 
           - 8082:8080

